### ISSUE TITLE
Current Roadmap

### ISSUE THREAD

**Issue by Divesh-Otwani** [tweag/linear-base#101]
# Roadmap (roughly in order)

* [ ] Organizational changes to clean things up
* [ ] Build out variants of the fundamentals from [`base`] **along with a test
   suite**:
    * Control
      * [x] Applicative
      * [x] Monad
    * Data
      * [x] Bifunctor
      * [ ] Bits
      * [x] Bool
      * [ ] Char
      * [x] Either
      * [x] Eq
      * [ ] Fixed
      * [ ] Foldable
      * [x] Functor
      * [x] Int (done via Num)
      * [x] List
      * [x] Maybe
      * [x] Ord
      * [x] Monoid
      * [ ] Ratio
      * [ ] Proxy
      * [x] Semigroup (done via Num)
      * [ ] String
      * [x] Tuple
    * [ ] Numeric.Natural
    * [ ] Prelude (almost done)
* [ ] Build out and clean up mutable data structures. Aim to make them fast. Have elegant property tests.
* [ ] Consider, document and possibly improve the design of
    * [ ] Push and pull arrays
    * [ ] The whole lens story
    * [ ] The non-GC-heap allocation
    * [ ] Linear IO
* [ ] Examples
  * [ ] A mutate-record kind of interface where you can mutate a copy of an object in some closed context. See the `Env` application in the basecamp post.
  * [ ] Another practical real world example. Investigate the list [here](https://3.basecamp.com/4151591/buckets/16502690/messages/2561826302#__recording_2562431873). Some top contenders: [ixy-languages], allocation free Haskell.
* [ ] The backlog

# Backlog
 * Other open issues
 * When multiplicity is supported, anything that can be made polymorphic should
   be made polymorphic -- this will make things much more sane.
 * There are a lot of old branches that need to be reviewed.

# Checklist for Release

 * [ ] A built haddock page (maybe a github page) with linear arrows rendered properly
 * [ ] Tutorials

[`base`]: https://hackage.haskell.org/package/base
[ixy-languages]: https://github.com/ixy-languages/ixy-languages

**Comment by Divesh-Otwani** [comment]
Closing because this is not a proper focused issue.
